# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  TUCAN_DEV: true

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: deps
          ignore_words_list: tucan
  build:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.17.0"
            otp: "27.0"
          - elixir: "1.16.2"
            otp: "26.1"
            lint: true
          - elixir: "1.15.6"
            otp: "26.1"

    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{matrix.elixir}}-${{matrix.otp}}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get
    - name: Compile with warnings enabled
      run: mix compile --force --warnings-as-errors
    - name: Format
      run: mix format --check-formatted
      if: ${{ matrix.lint }}
    - name: Credo
      run: mix credo --strict
      if: ${{ matrix.lint }}
    - name: Doctor
      run: mix doctor --failed
      if: ${{ matrix.lint }}
    - name: Run tests
      run: mix test --cover
      if: ${{ matrix.lint }}
    - name: Dialyzer
      run: mix dialyzer --format dialyxir --format dialyxir --error_handling --extra_return --underspecs --unmatched_returns
      if: ${{ matrix.lint }}
